proj_five/app_five/urls.py
from django.urls import path, re_path as url
from app_five import views

#TEMPLATE URLS !!
app_name = 'app_five'

urlpatterns = [
    url(r'^register/$',views.register, name='register'),
    url(r'^user_login/$',views.user_login, name='user_login'),
]

proj_five/proj_five/urls.py
from django.contrib import admin
from django.urls import path, re_path as url, include
from app_five import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    path('admin/', admin.site.urls),
    url(r'^app_five/', include('app_five.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/', views.special, name='special'),

]

proj_five/app_five/models.py
from django.db import models
#this User (class) here is Django's build in, that y u will not see it specificaly mentioned here.
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)

    # addtionaol classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

proj_five/app_five/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from app_five.models import UserProfileInfo


# user is an inbuilt in django which provides itself with username, first name last name email etc.
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
#above one is only for password field, we want it save even admin cannot see it.
    class Meta():
        model = User
        fields = ('username', 'email','password')

#profile info is custom made.. we are adding 2 fields here 1) portfolio_site and 2) pic
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

proj_five/app_five/views.py
from django.shortcuts import render
from app_five.forms import UserForm,UserProfileInfoForm

#for login all the imports tat are required:
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
#from django.contrib.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    return render(request, 'app_five/index.html')

@login_required
def special(request):
    return HttpResponse("Nice! You are logged in !")

#this decorators is required here in order to show logout only when there is already login done.
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password) #set method - so that this will encrpt or hide from all users.
            user.save()

            profile = profile_form.save(commit=False) #marked false in order to avoid commit conflict with users data like name and password etc.Remember that this is customed data that we have added.
            profile.user = user

            if 'profile_pic' in request.FILES: #request.FILES for all capturing images in the posted data.
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'app_five/registration.html',{'user_form':user_form, 'profile_form':profile_form,'registered':registered})
    #3rd argument is context which is dictionary sending 3 parameters in K,V pair - user_form, profile_form, registered.

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Account Inactive")
        else:
            print("SomeOne tried to login and Failed!!")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("Invalid User detail supplied!")
    else:
        return render(request,'app_five/login.html',{})

proj_five/app_five/templates/app_five/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">My Blog</a></li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li> <a class="navbar-link" href="{% url 'app_five:register' %}">REGISTER</a></li>

            {% if user.is_authenticated %}
            <li> <a class="navbar-link" href="{% url 'logout' %}">Logout</a> </li>
            {% else %}
            <li> <a class="navbar-link" href="{% url 'app_five:user_login' %}">Login</a> </li>
            {% endif %}

        </ul>
      </div>
    </nav>
<div class="container">
  {% block body_block %}

  {% endblock %}
</div>


  </body>
</html>

proj_five/app_five/templates/app_five/index.html
{% extends "app_five/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Stay Tuned !! My Blog Coming Soon!!</h1>

  </div>

</div>


{% endblock %}

proj_five/app_five/templates/app_five/login.html
{% extends 'app_five/base.html' %}

{% block body_block %}

<div class="jumbotron">
  <h1>Please Login!</h1>
<!-- we are using action here in the form -->
  <form action="{% url 'app_five:user_login' %}" method="post">

    {% csrf_token %}
    <label for="username">UserName:</label>
    <input type="text" name="username" placeholder="Enter UserName">

    <label for="password">Password</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>

</div>


{% endblock %}

proj_five/app_five/templates/app_five/registration.html
{% extends 'app_five/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for register!</h1>
  {% else %}
    <h1>Register here :</h1>
    <h3>Fill out the form :</h3>


    <form method="post" enctype="multipart/form-data">

      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <input type="submit" name="" value="Register">

    </form>

    {% endif %}


</div>


{% endblock %}